kits:
  warrior:
    activateMessage:
      message: "<red>You arrived to battle as a warrior!"
      broadcast: false

    attributes:
      - type: "MAX_HEALTH"
        amount: 10.0

    items:
      - material: "DIAMOND_AXE"
        name: "<b><red>Hardened sword"
        lore:
          - ""
          - "<green>[Right] <white>- click to activate ability"
          - "Launches you forward and upward"
          - "Gives you fall damage immunity for 4 sec"
          - "Cooldown (15 s)"
        enchantments:
          unbreaking: 4

      - material: "IRON_HELMET"
        name: "<red>Helmet"
        lore:
          - ""
          - "<gray>Rusty helmet."
        enchantments:
          unbreaking: 3

      - material: "DIAMOND_CHESTPLATE"
        name: "<b><red>Hardened plate"
        lore:
          - ""
          - "Be proud wearing it."
        enchantments:
          protection: 4
          unbreaking: 3
        trimMaterial: "iron"
        trimPattern: "sentry"

      - material: "IRON_LEGGINGS"
        name: "<red>Leggings"
        lore:
          - ""
          - "Rusty leggings."
        enchantments:
          unbreaking: 3
      - material: "IRON_BOOTS"
        name: "<red>Boots"
        lore:
          - ""
          - "Rusty boots."
        enchantments:
          unbreaking: 3

      - material: "POTION"
        name: "<red><u>Battle Potion"
        potionColor: "#BD1313"
        potionEffects:
          - type: "STRENGTH"
            durationSeconds: 120
            amplifier: 1
          - type: "REGENERATION"
            durationSeconds: 15
            amplifier: 1

    customItems:
      - id: RADIANCE_SHROOM

    kitAttributes:
      rampage: 2

  archer:
    activateMessage:
      message: "<green>You arrived to battle an archer!"
      broadcast: false

    attributes:
      - type: "MAX_HEALTH"
        amount: 4.0

    items:
      - material: "BOW"
        name: "<b><green>Light bow"
        lore:
          - ""
          - "<green>[Left] <white>- click to activate ability"
          - "Launches you backwards and lets you fall down slowly"
          - "Cooldown (10 s)"
        enchantments:
          unbreaking: 4

      - material: "CHAINMAIL_HELMET"
        name: "<green>Helmet"
        lore:
          - ""
          - "Old piece of armor"
        enchantments:
          unbreaking: 3
          projectile_protection: 1

      - material: "LEATHER_CHESTPLATE"
        name: "<b><green>Light plate"
        lore:
          - ""
          - "Light as a feather."
        enchantments:
          protection: 4
          unbreaking: 3
          projectile_protection: 3
        trimMaterial: "iron"
        trimPattern: "raiser"

      - material: "CHAINMAIL_LEGGINGS"
        name: "<green>Leggings"
        lore:
          - ""
          - "Old piece of armor"
        enchantments:
          unbreaking: 3
          projectile_protection: 1
      - material: "CHAINMAIL_BOOTS"
        name: "<green>Boots"
        lore:
          - ""
          - "Old piece of armor"
        enchantments:
          unbreaking: 3
          projectile_protection: 1

      - material: "POTION"
        name: "<green><u>Agility Potion"
        potionColor: "#BD1313"
        potionEffects:
          - type: "SPEED"
            durationSeconds: 120
            amplifier: 1
          - type: "JUMP_BOOST"
            durationSeconds: 15
            amplifier: 1

    kitAttributes:
      rampage: 1

  builder:
    activateMessage:
      message: "<green>You arrived to battle a builder!"
      broadcast: false

    attributes:
      - type: "MAX_HEALTH"
        amount: 2.0

    items:
      - material: "IRON_HELMET"
        name: "<gray><b>Builder's helmet"
        lore:
          - ""
          - "Your head has never been heavier"
        enchantments:
          protection: 4
          unbreaking: 3
          feather_falling: 2
          blast_protection: 1
        trimMaterial: "copper"
        trimPattern: "dune"

      - material: "COPPER_CHESTPLATE"
        name: "<b><green>Rusty plate"
        enchantments:
          unbreaking: 3
          blast_protection: 1

      - material: "COPPER_LEGGINGS"
        name: "<green>Leggings"
        enchantments:
          unbreaking: 3
          blast_protection: 1

      - material: "COPPER_BOOTS"
        name: "<green>Boots"
        enchantments:
          unbreaking: 3
          blast_protection: 1

    kitAttributes:
      rampage: 1

  elf:
    activateMessage:
      message: "<b><green>Elf from Mirkwood has arrived"
      broadcast: true

    attributes:
      - type: "MAX_HEALTH"
        amount: 20.0
      - type: "FALL_DAMAGE_MULTIPLIER"
        amount: -1.0

    potions:
      - type: "SPEED"
        durationSeconds: 1000000
        amplifier: 1
      - type: "JUMP_BOOST"
        durationSeconds: 1000000
        amplifier: 1

    items:
      - material: "BOW"
        name: "<b><green>Nature's Wrath"
        lore:
          - ""
          - "<green>[Left] <white>- click to activate ability"
          - "Stand still to craft new arrows, crafting takes 3 seconds"
          - "Cooldown 4 seconds"
        enchantments:
          power: 2
          punch: 1
          unbreaking: 3

      - material: "DIAMOND_PICKAXE"
        name: "<b><green>Elven Blade"
        lore:
          - ""
          - "<green>[Right] <white>- click to activate ability"
          - "Launches you in in the direction your are looking"
          - "Cooldown 8 seconds"
        enchantments:
          sharpness: 4
          unbreaking: 3

      - material: "LEATHER_HELMET"
        name: "<b><green>Light Helmet"
        lore:
          - ""
          - "Forged by the elves of Mirkwood"
        enchantments:
          protection: 3
          projectile_protection: 2
          unbreaking: 3
        trimMaterial: "emerald"
        trimPattern: "silence"

      - material: "LEATHER_CHESTPLATE"
        name: "<b><green>Light Plate"
        lore:
          - ""
          - "Forged by the elves of Mirkwood"
        enchantments:
          protection: 3
          projectile_protection: 2
          unbreaking: 3
        trimMaterial: "emerald"
        trimPattern: "silence"

      - material: "LEATHER_LEGGINGS"
        name: "<b><green>Light Leggings"
        lore:
          - ""
          - "Forged by the elves of Mirkwood"
        enchantments:
          protection: 3
          projectile_protection: 2
          unbreaking: 3
        trimMaterial: "emerald"
        trimPattern: "silence"

      - material: "LEATHER_BOOTS"
        name: "<b><green>Light Boots"
        lore:
          - ""
          - "Forged by the elves of Mirkwood"
        enchantments:
          protection: 3
          projectile_protection: 2
          unbreaking: 3
        trimMaterial: "emerald"
        trimPattern: "silence"

    customItems:
      - id: RADIANCE_SHROOM
        amount: 3
      - id: PURIFYING_LEAF
        amount: 4
      - id: RADIANCE_TORCH
        amount: 6

    kitAttributes:
      rampage: 1

  shaman:
    activateMessage:
      message: "<b><green>Shaman has arrived"
      broadcast: true

    attributes:
      - type: "MAX_HEALTH"
        amount: 20.0

    kitAttributes:
      rampage: 0

  zombie:
    activateMessage:
      message: "<green>You arrived to battle as a zombie"
      broadcast: false

    items:
      - material: "WOODEN_SWORD"
        name: "<b><dark_green>Rotten blade"
        enchantments:
          sharpness: 2
          unbreaking: 3

    kitAttributes:
      rampageImmune: false

  super_creeper:
    activateMessage:
      message: "<green>You arrived to battle as a super creeper"
      broadcast: false

    kitAttributes:
      rampageImmune: false

  enderman:
    activateMessage:
      message: "<dark_purple>Enderman the lord of shadows has arrived!"
      broadcast: true

    potions:
      - type: "ABSORPTION"
        durationSeconds: 1000000
        amplifier: 14
      - type: "SPEED"
        durationSeconds: 1000000
        amplifier: 0
      - type: "RESISTANCE"
        durationSeconds: 1000000
        amplifier: 2

    items:
      - material: "COMPASS"
        name: "<b><dark_purple>Teleport"
        lore:
          - ""
          - "Teleport to the block you are looking at in the range of 40 blocks."
          - "Cooldown <gray>10s"
          - "<green>[Right] <white>- click to use"
      - material: "WARD_ARMOR_TRIM_SMITHING_TEMPLATE"
        name: "<b><dark_purple>Scream"
        lore:
          - ""
          - "Scream at your enemies damaging them and reducing their movements."
          - "Cooldown <gray>15s"
          - "<green>[Right] <white>- click to use"

    kitAttributes:
      rampageImmune: false

  skeleton:
    activateMessage:
      message: "<aqua>You arrived to battle as a skeleton"
      broadcast: false

    items:
      - material: "BOW"
        name: "<b><aqua>Dusty Bow"
      - material: "ARROW"
        name: "<gray>Arrow"
        amount: 32

    kitAttributes:
      rampageImmune: false

  creeper:
    activateMessage:
      message: "<green>You arrived to battle as a creeper"
      broadcast: false

    kitAttributes:
      rampageImmune: false

  iron_golem:
    activateMessage:
      message: "<white>You arrived to battle as an Iron Golem"
      broadcast: false

    potions:
      - type: "REGENERATION"
        durationSeconds: 1000000
        amplifier: 1
      - type: "ABSORPTION"
        durationSeconds: 1000000
        amplifier: 34
      - type: "RESISTANCE"
        durationSeconds: 1000000
        amplifier: 3

    items:
      - material: "COPPER_PICKAXE"
        name: "<b><white>Old pickaxe"
        enchantments:
          unbreaking: 10

      - material: "COPPER_HELMET"
        name: "<b><dark_purple>Cursed Helmet"
        enchantments:
          binding_curse: 1
        attributes:
          - type: "KNOCKBACK_RESISTANCE"
            amount: 1.0
            slot: "HEAD"
          - type: "ATTACK_DAMAGE"
            amount: 10.0
            slot: "HEAD"

    kitAttributes:
      rampageImmune: true

  spider:
    activateMessage:
      message: "<green>You arrived to battle as a spider"
      broadcast: false

    potions:
      - type: "ABSORPTION"
        durationSeconds: 1000000
        amplifier: 9
      - type: "SPEED"
        durationSeconds: 1000000
        amplifier: 1
      - type: "WEAVING"
        durationSeconds: 1000000
        amplifier: 0
      - type: "JUMP_BOOST"
        durationSeconds: 1000000
        amplifier: 1
      - type: "RESISTANCE"
        durationSeconds: 1000000
        amplifier: 1

    items:
      - material: "SPIDER_EYE"
        name: "<dark_green>Spider's bite"
        lore:
          - ""
          - "Gives dwarves negative effects on hitting them"
        enchantments:
          sharpness: 5

    kitAttributes:
      rampageImmune: false

  witch:
    activateMessage:
      message: "<green>You arrived to battle as a witch"
      broadcast: false

    potions:
      - type: "ABSORPTION"
        durationSeconds: 1000000
        amplifier: 19
      - type: "SPEED"
        durationSeconds: 1000000
        amplifier: 1
      - type: "RESISTANCE"
        durationSeconds: 1000000
        amplifier: 2

    kitAttributes:
      rampageImmune: false