kits:
  warrior:
    activateMessage:
      message: "<red>You arrived to battle as a warrior!"
      broadcast: false

    attributes:
      - type: "MAX_HEALTH"
        amount: 10.0

    items:
      - material: "DIAMOND_CHESTPLATE"
        name: "<b><red>Hardened plate"
        lore:
          - "<gray>Be proud wearing it."
        enchantments:
          protection: 4
          unbreaking: 3
        trimMaterial: "iron"
        trimPattern: "sentry"

      - material: "POTION"
        name: "<red><u>Battle Potion"
        potionColor: "#BD1313"
        potionEffects:
          - type: "STRENGTH"
            durationSeconds: 120
            amplifier: 2

    customItems:
      - id: RADIANCE_SHROOM

    kitAttributes:
      rampage: 2

  archer:
    activateMessage:
      message: "<green>You arrived to battle an archer!"
      broadcast: false

    attributes:
      - type: "MAX_HEALTH"
        amount: 4.0

    items:
      - material: "LEATHER_CHESTPLATE"
        name: "<b><green>Light plate"
        lore:
          - "<gray>Light as feather."
        enchantments:
          protection: 4
          unbreaking: 3

    kitAttributes:
      rampage: 1

  elf:
    activateMessage:
      message: "<green>Elf from Mirkwood has arrived"
      broadcast: true

    attributes:
      - type: "MAX_HEALTH"
        amount: 20.0

    items:
      - material: "BOW"
        name: "<b><green>Nature's Wrath"
        enchantments:
          power: 5
          punch: 2
          unbreaking: 3

    kitAttributes:
      rampage: 1

  zombie:
    activateMessage:
      message: "<green>You arrived to battle as a zombie"
      broadcast: false

    items:
      - material: "WOODEN_SWORD"
        name: "<b><dark_green>Rotten blade"
        enchantments:
          sharpness: 2
          unbreaking: 3

    kitAttributes:
      rampageImmune: false
  super_creeper:
    activateMessage:
      message: "<green>You arrived to battle as a super creeper"
      broadcast: false

    items:
      - material: "GUNPOWDER"
        name: "<b><dark_green>boom"

    kitAttributes:
      rampageImmune: false
  enderman:
    activateMessage:
      message: "<green>You arrived to battle as an enderman"
      broadcast: false

    items:
      - material: "ENDER_PEARL"
        name: "<b><dark_green>pearl"

    kitAttributes:
      rampageImmune: false