name: DvZ
version: '1.0-SNAPSHOT'
main: com.jackob.dvz.DvZ
api-version: '1.21'
description: Dwarves vs Zombies minigame
dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
    Multiverse-Core:
      load: BEFORE
      required: false
    WorldEdit:
      load: BEFORE
      required: true
    WorldGuard:
      load: BEFORE
      required: true
    LibsDisguises:
      load: BEFORE
      required: true