package com.jackob.dvz.kits.zombie.base

enum class CreeperUpgrades {
    SHALLOW_WOUND_I,
    SHALLOW_WOUND_II,
    SHALLOW_WOUND_III,
    WALL_CRUSHER_I,
    WALL_CRUSHER_II,
    WALL_CRUSHER_III,
    HARDENING_I,
    SHEEPS_CLOTHING_I,
    SHEEPS_CLOTHING_II,
    SHEEPS_CLOTHING_III,
    CHAIN_REACTION_I,
    CHAIN_REACTION_II,
    CHAIN_REACTION_III,
    NITROGLYCERIN_I,
    NITROGLYCERIN_II,
    NITROGLYCERIN_III,
}