package com.jackob.dvz.kits.zombie.base

enum class SkeletonUpgrade {
    CLOAK_I,
    CLOAK_II,
    CLOAK_III,
    ARMORY_I,
    ARMORY_II,
    ARMORY_III,
    LEATHER_QUIVER_I,
    LEATHER_QUIVER_II,
    LEATHER_QUIVER_III,
    LEATHER_QUIVER_IV,
    SLIM_BLADE_I,
    SLIM_BLADE_II,
    POISONED_ARROW_I,
    POISONED_ARROW_II,
    BAG_OF_BONES_I,
    BAG_OF_BONES_II,
    BAG_OF_BONES_III,
    BAG_OF_BONES_IV,
    ABRUPT_MOVEMENTS_I,
    ABRUPT_MOVEMENTS_II,
    ABRUPT_MOVEMENTS_III,
    FIXED_TARGET_I,
    FIXED_TARGET_II,
    FIXED_TARGET_III,
    SKINLESS_I
}